/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Apps.Cliente;
import Tempo.Tclock;
import Tempo.Temporizador;
import javax.swing.JButton;
import javax.swing.JToggleButton;
import javax.swing.Timer;

/**
 *
 * @author Leonardo Fronza
 */
public class Clientes extends javax.swing.JFrame {

    Tclock tempo;
    Cliente c;

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        c = new Cliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btPegarKey = new javax.swing.JButton();
        lbHora = new javax.swing.JLabel();
        lbKey = new javax.swing.JLabel();
        lbTempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btPegarKey.setText("Pegar key");
        btPegarKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPegarKeyActionPerformed(evt);
            }
        });

        lbHora.setText("Hora =");

        lbKey.setText("Key =");

        lbTempo.setText("Tempo =");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btPegarKey))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbKey, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHora, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(87, 87, 87)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbHora)
                .addGap(18, 18, 18)
                .addComponent(lbKey)
                .addGap(18, 18, 18)
                .addComponent(lbTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(btPegarKey)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPegarKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPegarKeyActionPerformed
        btPegarKey.setEnabled(false);
        lbHora.setText("Hora = " + c.getHora());
        lbKey.setText("Key = " + c.getKey());
        tempo = new Tclock(this, 60.0);
        tempo.start();
    }//GEN-LAST:event_btPegarKeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    public void setTempo(String tempo) {
        if (Double.parseDouble(tempo) < 60.0) {
            lbTempo.setText("Tempo = " + ((Double.parseDouble(tempo) - 60.0)) * (-1));
        } else {
            resetar();
        }

    }

    public JButton getBotao() {
        return btPegarKey;
    }

    public void resetar() {
        btPegarKey.setEnabled(true);
        lbHora.setText("Hora = ");
        lbKey.setText("Key = ");
        lbTempo.setText("Tempo = ");
        tempo.parar();
        tempo = null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPegarKey;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbKey;
    private javax.swing.JLabel lbTempo;
    // End of variables declaration//GEN-END:variables
}
